Fixed introduced cmake error (undefined reference)
Changed order of libUserRoot and libKinFitter, link KinFitter against
UserRoot in order to use TKinFitter methods properly -> fixed
"libUserRoot.so: undefined reference to `TKinFitter::*'"